{% set name = "pyroll-cli" %}
{% set version = "3.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyroll_cli-{{ version }}.tar.gz
  sha256: 0879b82a207b9e460a7c437f07ea3543219eff9cd3aa17bd5d8188471cd581ed

build:
  entry_points:
    - pyroll = pyroll.cli.program:run_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyroll-core >=3.0,<4.dev0
    - click >=8.0,<9.dev0
    - tomli >=2.0,<3.dev0
    - tomli-w >=1.0,<2.dev0
    - jinja2 >=3.0,<4.dev0
    - rich >=13.0,<14.dev0
    - click-repl >=0.2,<1.dev0

test:
  imports:
    - pyroll.cli
  commands:
    - pip check
    - pyroll --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyroll.readthedocs.io
  summary: PyRoll rolling simulation framework - command line interface (CLI).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
